// lib/licensing/keys.ts
//
// The public half of the XenithPulse licence signing key.
//
// ── Why this is a compiled-in constant and not a setting ────────────────────
//
// It is tempting to make this configurable - a POS_LICENSE_PUBLIC_KEY in .env
// would be convenient for testing. It would also be a documented bypass: the
// live .env sits in C:\ProgramData\XP POS on the customer's own box, readable
// and writable by anyone who can open Notepad as Administrator there. Swapping
// this value for a self-generated one turns "defeat the licensing" into a
// two-minute job with no tools. So it is a constant, changed by shipping a
// build, and the private half never leaves XenithPulse.
//
// This is a PUBLIC key. It is meant to ship in every installer and there is
// nothing to protect about it. What it buys is that a licence can only be
// MINTED by whoever holds the private half - a symmetric secret in the
// installer would let anyone who extracted it issue their own, and the app is
// minified JavaScript, so extracting it is an afternoon.
//
// Base64 of the DER SPKI encoding of an Ed25519 public key. Generated by
// tools/licensing/keygen.mjs, which prints exactly this line.
//
// ── Rotating it ─────────────────────────────────────────────────────────────
//
// Do not. Every licence in the field was signed by the matching private key,
// and a new key invalidates all of them on the next upgrade - which is a fleet
// of paying restaurants dropping into a 14-day grace period at once. If the
// private key is ever compromised, that is a planned migration with a build
// that trusts both keys during the overlap, not an edit to this line.

export const LICENSE_PUBLIC_KEY_SPKI_BASE64 =
  "MCowBQYDK2VwAyEAMMXirCOr1YZ1YhL1y+k/hcxqBvDMzDJuVK2SVtlV4X0=";

/** True when this build can check a licence at all. Asserted by build.ps1. */
export function hasLicensePublicKey(): boolean {
  return LICENSE_PUBLIC_KEY_SPKI_BASE64.trim().length > 0;
}
